### ISSUE TITLE
Bug when fruit generated on snake's body

### ISSUE THREAD

**Issue by livibetter** [FedeDP/Snake#5]
I noticed when the snake becomes longer and there is a better chance next fruit will be generated on the body. Actually, more like under the body. The fruit is printed once, then the body is printed on top of fruit, but as the body crawling away, the fruit isn't reprinted, since it only is printed once upon the generation.

An easy fix is to re-print the fruit right after the snake is printed in `snake_move`, however, I don't think that's a correct solution, `fruit_gen` should check if new fruit happens to be on the body, then generate again. It will make more sense, but doesn't have to be. The easy fix is fine.

And this is why I am not trying to create a pull request, the decision isn't mine.

To reproduce the issue is fairly simple, don't have to play for a long time, just reduce the `ROWS` into 1, and watch you will see the red fruit is gone from screen but the snake still eats the invisible fruits and grows.

With the original size, I had to save and resume to see where the fruit is at, or I almost got no chance to find that invisible fruit.

**Comment by FedeDP** [comment]
It is now fixed.
Thanks for the report! The issue happened when the fruit was generated next to the snake head (in the right direction obviously). The fruit just spawned was overwritten by the snake movement in that direction. I just anticipated the snake movement before calling eat_fruit() (L 236,237 in master now).

Again, really thanks for your time :)
